
ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autofix_commit_msg: "fix(pre_commit): 🎨 auto format pre-commit hooks"
  autoupdate_commit_msg: "chore(pre_commit): ⬆ pre_commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
    - id: markdownlint
      args: ['--disable','MD013','MD024','--fix']
      exclude: docs/index.md
